### ISSUE TITLE
bundle doesn't exist (while this is not true)

### ISSUE THREAD

**Issue by Edwin-Luijten** [sparksp/laravel-apigen#2]
When I run apigen::make:bundle I get the following error:
Source "--apigensourcepath--" --source=--bundlesourcepath--""

*note those two "" at the end, I guess the need to be around --bundlesourcepath--, I can't find the line in the apigen bundle files where the commands are made.

When I do apigen::make:bundle swiftmailer or any other single bundle all goes well.

**Comment by aleemb** [comment]
To fix this, update line 199 include a call to `addslashes`:

```
            $output .= $name.escapeshellarg(addslashes($value));
```

Since the directory separator on windows is `\` the last quotation `"a\b\c"` in gets escaped and breaks things.

**Comment by sparksp** [comment]
@aleemb that seems reasonable - I was surprised to read that `escapeshellarg` doesn't do this for you.  How will this affect non-windows people?

**Comment by aleemb** [comment]
@sparksp not sure about non-windows users. Just had a look at `escapeshellarg` and the docs say that it escapes any single quotes in the string. `addslahes` also escapes single quotes so there is a potential for conflict depending on the order of execution. The other alternative might be to replace `\` in all paths with `/` somewhere else in your code, since `/` as a directory separator works fine in windows as well.

**Comment by sparksp** [comment]
Archiving this repo
